version: '3.8'

services:
  backend:
    build: .
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data  # Persist SQLite database

volumes:
  sqlite_data:
